include $(srctree)/drivers/misc/mediatek/Makefile.custom


ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

#target
obj-y   +=  synaptics_dsx_fw_update.o
obj-y   +=  synaptics_dsx_i2c.o
obj-y   +=  synaptics_dsx_rmi_dev.o
obj-y   +=  synaptics_dsx_test_reporting.o